"""added in tag categories

Revision ID: 4af3c4d61f5c
Revises: 9e23510c18a0
Create Date: 2023-06-21 10:42:11.876493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af3c4d61f5c'
down_revision = '9e23510c18a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('risk_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('trade_duration', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('trade_outcome', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('trade_outcome')
        batch_op.drop_column('trade_duration')
        batch_op.drop_column('risk_level')
        batch_op.drop_column('sector')

    # ### end Alembic commands ###
